### ISSUE TITLE
compiling with make fails

### ISSUE THREAD

**Issue by moritzgubler** [szaghi/StringiFor#36]
It seems to me that the current makefile does not compile the third party part of the library. make in the base directory returns:

Compile penf_global_parameters_variables.F90
Compile penf_b_size.F90
Compile penf_stringify.F90
Compile penf.F90
Compile befor64_pack_data_m.F90
Compile befor64.F90
Compile stringifor_string_t.F90
src/lib/stringifor_string_t.F90:6:4:
6 | use face, only : colorize
|    1
Fatal Error: Cannot open module file ‘face.mod’ for reading at (1): No such file or directory
compilation terminated.
make: *** [makefile:413: lib/obj/stringifor_string_t.o] Error

Am I supposed to compile and install the libraries in src/third_party manually or is this a bug in the makefile?

**Comment by szaghi** [comment]
Hi @moritzgubler 

It is due (probably) to the fact that the makefile is not up-to-date. I'll try to fix it ASAP

**Comment by szaghi** [comment]
Hi @moritzgubler 

I have just pushed a new release with an updated makefile, it seems to work for me. Please let me know if it fixes the issue also for you. Note that the `third_party` libraries are supposed to be compiled automatically by means of fobos/makefile, but be sure to have the sources downloaded, e.g. cloning the repository an all submodules with recursive cloning.

Thank you for reporting the bug, cheers

**Comment by moritzgubler** [comment]
Hi @szaghi 
Thanks for the quick fix. Make now successfully builds the library. The tests are also not working. 
make TESTS=yes returns
make: *** No rule to make target `src/tests/is_real.f90', needed by `exe/obj/is_real.o'.  Stop.

Cheers,
Moritz

**Comment by szaghi** [comment]
Hi @moritzgubler 

I have just uploaded a new fix, let me know if you are able to compile and run tests.

Cheers

**Comment by moritzgubler** [comment]
Hi @szaghi 

Thanks for the update. I am still not able to test the library.  make TESTS=yes now returns: make: *** No rule to make target `exe/STRINGIFOR_TEST_CSV_NAIVE_PARSER', needed by `.NOTPARALLEL'.  Stop.

This is the case for a freshly pulled repository without any old executables laying around.

Cheers
Moritz

**Comment by szaghi** [comment]
@moritzgubler 

I have just pushed a fix, there was a typo on the csv naive parser test rule.

Let me know if this works also for you (I am able to compile all tests with also the makefile, I use FoBiS that is the official building tool).

Cheers

**Comment by moritzgubler** [comment]
The tests are now also working. Thanks for fixing this.

**Comment by szaghi** [comment]
@moritzgubler you are welcome
